// ============================================================
// RazorX — Seed Data: 4 Verified Merchants, 26 Realistic Products
// With High-Definition Cloud / CDN Product Photography
// ============================================================

import type { Merchant, MerchantPolicy, Product } from '../types.js';

// ---- Verified Merchants ----
export const seedMerchants: Merchant[] = [
  {
    id: 'merchant-runpro',
    name: 'RunPro Sports',
    slug: 'runpro-sports',
    description: 'Premium running and fitness gear for serious athletes',
    logo_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=120&auto=format&fit=crop&q=80',
    rating: 4.8,
    reliability_score: 0.96,
    categories: ['running_shoes', 'fitness', 'accessories'],
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'merchant-technest',
    name: 'TechNest Electronics',
    slug: 'technest',
    description: 'Smart electronics, audio gear, and gadgets at competitive prices',
    logo_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=120&auto=format&fit=crop&q=80',
    rating: 4.7,
    reliability_score: 0.94,
    categories: ['electronics', 'accessories'],
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'merchant-campusmart',
    name: 'CampusMart Essentials',
    slug: 'campusmart',
    description: 'Everything a student & professional needs — affordable, reliable, fast delivery',
    logo_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=120&auto=format&fit=crop&q=80',
    rating: 4.6,
    reliability_score: 0.91,
    categories: ['student_essentials', 'electronics', 'clothing', 'running_shoes'],
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'merchant-fitfuel',
    name: 'FitFuel Nutrition & Gear',
    slug: 'fitfuel',
    description: 'Fitness accessories, premium apparel, and pure nutrition for your health goals',
    logo_url: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=120&auto=format&fit=crop&q=80',
    rating: 4.8,
    reliability_score: 0.95,
    categories: ['fitness', 'nutrition', 'accessories', 'running_shoes'],
    created_at: '2025-01-01T00:00:00Z',
  },
];

// ---- Merchant Policies ----
export const seedMerchantPolicies: MerchantPolicy[] = [
  {
    id: 'policy-runpro',
    merchant_id: 'merchant-runpro',
    negotiation: true,
    max_discount: 0.10,
    auto_confirmation_limit: 25000,
    auto_refund_limit: 2000,
    upsell: true,
    max_upsell_offers: 2,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'policy-technest',
    merchant_id: 'merchant-technest',
    negotiation: true,
    max_discount: 0.07,
    auto_confirmation_limit: 50000,
    auto_refund_limit: 3000,
    upsell: true,
    max_upsell_offers: 3,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'policy-campusmart',
    merchant_id: 'merchant-campusmart',
    negotiation: true,
    max_discount: 0.12,
    auto_confirmation_limit: 15000,
    auto_refund_limit: 1000,
    upsell: false,
    max_upsell_offers: 0,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'policy-fitfuel',
    merchant_id: 'merchant-fitfuel',
    negotiation: true,
    max_discount: 0.08,
    auto_confirmation_limit: 20000,
    auto_refund_limit: 1500,
    upsell: true,
    max_upsell_offers: 2,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
];

// ---- Products Catalog with CDN Images ----
export const seedProducts: Product[] = [
  // ============ RunPro Sports ============
  {
    id: 'prod-rp-001', merchant_id: 'merchant-runpro',
    title: 'RunPro Velocity X Daily Trainer',
    category: 'running_shoes', subcategory: 'daily_training',
    description: 'Lightweight daily training shoe with responsive cushioning and breathable mesh upper. Perfect for everyday runs up to 10K.',
    price: 5799, original_price: 6499, currency: 'INR', stock: 45,
    variants: [
      { id: 'v-rp001-8', product_id: 'prod-rp-001', name: 'Size 8 - Black', sku: 'RP-VX-8-BLK', price: 5799, stock: 12, attributes: { size: '8', color: 'black' } },
      { id: 'v-rp001-9', product_id: 'prod-rp-001', name: 'Size 9 - Black', sku: 'RP-VX-9-BLK', price: 5799, stock: 15, attributes: { size: '9', color: 'black' } },
      { id: 'v-rp001-10', product_id: 'prod-rp-001', name: 'Size 10 - Black', sku: 'RP-VX-10-BLK', price: 5799, stock: 10, attributes: { size: '10', color: 'black' } },
      { id: 'v-rp001-9w', product_id: 'prod-rp-001', name: 'Size 9 - White', sku: 'RP-VX-9-WHT', price: 5799, stock: 8, attributes: { size: '9', color: 'white' } },
    ],
    attributes: { brand: 'RunPro', type: 'daily_trainer', cushioning: 'responsive', weight: '280g', drop: '8mm' },
    delivery_days: 3, rating: 4.7, image_url: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&auto=format&fit=crop&q=80', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-rp-002', merchant_id: 'merchant-runpro',
    title: 'RunPro Surge Pro Racing Flat',
    category: 'running_shoes', subcategory: 'racing',
    description: 'Carbon-plated racing shoe for competitive runners. Ultra-light with maximum energy return and aerodynamic design.',
    price: 8999, original_price: 9999, currency: 'INR', stock: 20,
    variants: [
      { id: 'v-rp002-9', product_id: 'prod-rp-002', name: 'Size 9 - Neon Green', sku: 'RP-SP-9-NGR', price: 8999, stock: 8, attributes: { size: '9', color: 'neon_green' } },
      { id: 'v-rp002-10', product_id: 'prod-rp-002', name: 'Size 10 - Neon Green', sku: 'RP-SP-10-NGR', price: 8999, stock: 6, attributes: { size: '10', color: 'neon_green' } },
    ],
    attributes: { brand: 'RunPro', type: 'racing', cushioning: 'carbon_plate', weight: '195g', drop: '6mm' },
    delivery_days: 2, rating: 4.9, image_url: 'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&auto=format&fit=crop&q=80', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-rp-003', merchant_id: 'merchant-runpro',
    title: 'RunPro CloudStride Comfort',
    category: 'running_shoes', subcategory: 'daily_training',
    description: 'Maximum cushioning for long-distance daily training. Cloud-foam midsole absorbs impact beautifully.',
    price: 4999, original_price: 5999, currency: 'INR', stock: 60,
    variants: [
      { id: 'v-rp003-8', product_id: 'prod-rp-003', name: 'Size 8 - Black', sku: 'RP-CS-8-BLK', price: 4999, stock: 15, attributes: { size: '8', color: 'black' } },
      { id: 'v-rp003-9', product_id: 'prod-rp-003', name: 'Size 9 - Black', sku: 'RP-CS-9-BLK', price: 4999, stock: 20, attributes: { size: '9', color: 'black' } },
      { id: 'v-rp003-9g', product_id: 'prod-rp-003', name: 'Size 9 - Grey', sku: 'RP-CS-9-GRY', price: 4999, stock: 15, attributes: { size: '9', color: 'grey' } },
      { id: 'v-rp003-10', product_id: 'prod-rp-003', name: 'Size 10 - Black', sku: 'RP-CS-10-BLK', price: 4999, stock: 10, attributes: { size: '10', color: 'black' } },
    ],
    attributes: { brand: 'RunPro', type: 'daily_trainer', cushioning: 'cloud_foam', weight: '310g', drop: '10mm' },
    delivery_days: 3, rating: 4.6, image_url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=600&auto=format&fit=crop&q=80', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-rp-004', merchant_id: 'merchant-runpro',
    title: 'RunPro TrailBlazer GTX',
    category: 'running_shoes', subcategory: 'trail',
    description: 'Waterproof trail running shoe with aggressive multi-directional grip. Built for rugged off-road terrain.',
    price: 6999, original_price: 7999, currency: 'INR', stock: 25,
    variants: [
      { id: 'v-rp004-9', product_id: 'prod-rp-004', name: 'Size 9 - Black/Orange', sku: 'RP-TB-9-BOR', price: 6999, stock: 10, attributes: { size: '9', color: 'black_orange' } },
      { id: 'v-rp004-10', product_id: 'prod-rp-004', name: 'Size 10 - Black/Orange', sku: 'RP-TB-10-BOR', price: 6999, stock: 8, attributes: { size: '10', color: 'black_orange' } },
    ],
    attributes: { brand: 'RunPro', type: 'trail', cushioning: 'rock_plate', weight: '340g', drop: '6mm', waterproof: 'yes' },
    delivery_days: 4, rating: 4.8, image_url: 'https://images.unsplash.com/photo-1539185441755-769473a23570?w=600&auto=format&fit=crop&q=80', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-rp-005', merchant_id: 'merchant-runpro',
    title: 'RunPro FlexRun Lite',
    category: 'running_shoes', subcategory: 'daily_training',
    description: 'Budget-friendly daily trainer with decent cushioning. Great entry-level running shoe for beginners.',
    price: 2999, original_price: 3499, currency: 'INR', stock: 80,
    variants: [
      { id: 'v-rp005-8', product_id: 'prod-rp-005', name: 'Size 8 - Black', sku: 'RP-FL-8-BLK', price: 2999, stock: 25, attributes: { size: '8', color: 'black' } },
      { id: 'v-rp005-9', product_id: 'prod-rp-005', name: 'Size 9 - Black', sku: 'RP-FL-9-BLK', price: 2999, stock: 30, attributes: { size: '9', color: 'black' } },
      { id: 'v-rp005-10', product_id: 'prod-rp-005', name: 'Size 10 - Blue', sku: 'RP-FL-10-BLU', price: 2999, stock: 25, attributes: { size: '10', color: 'blue' } },
    ],
    attributes: { brand: 'RunPro', type: 'daily_trainer', cushioning: 'eva_foam', weight: '260g', drop: '8mm' },
    delivery_days: 2, rating: 4.3, image_url: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=600&auto=format&fit=crop&q=80', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-rp-006', merchant_id: 'merchant-runpro',
    title: 'RunPro Compression Running Socks (3-Pack)',
    category: 'accessories', subcategory: 'socks',
    description: 'Moisture-wicking compression socks designed for runners. Ergonomic arch support and anti-blister padding.',
    price: 799, original_price: 999, currency: 'INR', stock: 200,
    variants: [],
    attributes: { brand: 'RunPro', material: 'nylon_blend', compression: 'medium' },
    delivery_days: 2, rating: 4.5, image_url: 'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?w=600&auto=format&fit=crop&q=80', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-rp-007', merchant_id: 'merchant-runpro',
    title: 'RunPro HydraFlask Running Bottle 500ml',
    category: 'accessories', subcategory: 'hydration',
    description: 'Ergonomic squeeze bottle designed for handheld running. Ultra-light soft flask with leak-proof bite valve.',
    price: 599, original_price: 699, currency: 'INR', stock: 150,
    variants: [],
    attributes: { brand: 'RunPro', capacity: '500ml', material: 'BPA-free silicone' },
    delivery_days: 2, rating: 4.4, image_url: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=600&auto=format&fit=crop&q=80', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },

  // ============ TechNest Electronics ============
  {
    id: 'prod-tn-001', merchant_id: 'merchant-technest',
    title: 'TechNest AirBuds Pro ANC Wireless Earbuds',
    category: 'electronics', subcategory: 'earbuds',
    description: 'Hybrid Active Noise Cancelling (ANC) wireless earbuds with 36hr battery life, spatial audio, and wireless charging case.',
    price: 4499, original_price: 5499, currency: 'INR', stock: 100,
    variants: [
      { id: 'v-tn001-blk', product_id: 'prod-tn-001', name: 'Obsidian Black', sku: 'TN-ABP-BLK', price: 4499, stock: 40, attributes: { color: 'black' } },
      { id: 'v-tn001-wht', product_id: 'prod-tn-001', name: 'Glacier White', sku: 'TN-ABP-WHT', price: 4499, stock: 35, attributes: { color: 'white' } },
    ],
    attributes: { brand: 'TechNest', type: 'TWS', anc: 'yes', battery: '36hrs', driver: '11mm' },
    delivery_days: 2, rating: 4.8, image_url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&auto=format&fit=crop&q=80', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-tn-002', merchant_id: 'merchant-technest',
    title: 'TechNest SmartBand Pulse HR',
    category: 'electronics', subcategory: 'wearable',
    description: 'Continuous heart rate, SpO2, and sleep tracker with vivid AMOLED display and 14-day battery life.',
    price: 2999, original_price: 3999, currency: 'INR', stock: 75,
    variants: [
      { id: 'v-tn002-blk', product_id: 'prod-tn-002', name: 'Black Strap', sku: 'TN-SBP-BLK', price: 2999, stock: 35, attributes: { color: 'black' } },
      { id: 'v-tn002-grn', product_id: 'prod-tn-002', name: 'Olive Strap', sku: 'TN-SBP-GRN', price: 2999, stock: 20, attributes: { color: 'green' } },
    ],
    attributes: { brand: 'TechNest', type: 'fitness_tracker', heart_rate: 'yes', spo2: 'yes', battery: '14days' },
    delivery_days: 2, rating: 4.5, image_url: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&auto=format&fit=crop&q=80', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-tn-003', merchant_id: 'merchant-technest',
    title: 'TechNest VoltBank 20000mAh 65W Fast Charge',
    category: 'electronics', subcategory: 'power_bank',
    description: 'High-capacity 20000mAh power bank with 65W Power Delivery. Charges laptops, MacBooks, and smartphones rapidly.',
    price: 1999, original_price: 2499, currency: 'INR', stock: 120,
    variants: [],
    attributes: { brand: 'TechNest', capacity: '20000mAh', fast_charge: '65W', ports: 'USB-C, USB-A' },
    delivery_days: 3, rating: 4.6, image_url: 'https://images.unsplash.com/photo-1609592424368-243003023027?w=600&auto=format&fit=crop&q=80', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-tn-004', merchant_id: 'merchant-technest',
    title: 'TechNest MiniSpeaker Blast IPX7',
    category: 'electronics', subcategory: 'speaker',
    description: 'Rugged portable Bluetooth 5.3 speaker with 360° deep bass sound and IPX7 waterproof rating. 16hr battery.',
    price: 3499, original_price: 4499, currency: 'INR', stock: 55,
    variants: [
      { id: 'v-tn004-blk', product_id: 'prod-tn-004', name: 'Midnight Black', sku: 'TN-MSB-BLK', price: 3499, stock: 25, attributes: { color: 'black' } },
      { id: 'v-tn004-red', product_id: 'prod-tn-004', name: 'Crimson Red', sku: 'TN-MSB-RED', price: 3499, stock: 15, attributes: { color: 'red' } },
    ],
    attributes: { brand: 'TechNest', type: 'portable_speaker', waterproof: 'IPX7', battery: '16hrs', bluetooth: '5.3' },
    delivery_days: 3, rating: 4.4, image_url: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=600&auto=format&fit=crop&q=80', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-tn-005', merchant_id: 'merchant-technest',
    title: 'TechNest UltraCharge 45W GaN Dual Port',
    category: 'electronics', subcategory: 'charger',
    description: 'Next-gen GaN 45W USB-C compact wall charger. Ultra-fast thermal dissipation and travel-friendly folding pins.',
    price: 1299, original_price: 1599, currency: 'INR', stock: 200,
    variants: [],
    attributes: { brand: 'TechNest', type: 'charger', wattage: '45W', technology: 'GaN', ports: 'USB-C + USB-A' },
    delivery_days: 2, rating: 4.7, image_url: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=600&auto=format&fit=crop&q=80', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-tn-006', merchant_id: 'merchant-technest',
    title: 'TechNest ProWatch Ultra Stainless Steel',
    category: 'electronics', subcategory: 'smartwatch',
    description: 'Flagship smartwatch with 1.43" AMOLED sapphire glass, dual-frequency GPS, Bluetooth calling, and 7-day battery.',
    price: 8499, original_price: 9999, currency: 'INR', stock: 30,
    variants: [
      { id: 'v-tn006-blk', product_id: 'prod-tn-006', name: 'Black Steel', sku: 'TN-PWU-BLK', price: 8499, stock: 15, attributes: { color: 'black', material: 'stainless_steel' } },
      { id: 'v-tn006-slv', product_id: 'prod-tn-006', name: 'Silver Steel', sku: 'TN-PWU-SLV', price: 8499, stock: 15, attributes: { color: 'silver', material: 'stainless_steel' } },
    ],
    attributes: { brand: 'TechNest', type: 'smartwatch', display: 'AMOLED', gps: 'yes', battery: '7days' },
    delivery_days: 3, rating: 4.8, image_url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },

  // ============ CampusMart Essentials ============
  {
    id: 'prod-cm-001', merchant_id: 'merchant-campusmart',
    title: 'CampusMart StudyBeam LED Smart Lamp',
    category: 'student_essentials', subcategory: 'lamp',
    description: 'Eye-care dimmable LED desk lamp with 5 color temperatures, wireless phone charging pad, and auto-off timer.',
    price: 1499, original_price: 1999, currency: 'INR', stock: 90,
    variants: [],
    attributes: { brand: 'CampusMart', type: 'desk_lamp', brightness_levels: '5', wireless_charger: 'yes' },
    delivery_days: 3, rating: 4.4, image_url: 'https://images.unsplash.com/photo-1534353436294-0dbd4bdac845?w=600&auto=format&fit=crop&q=80', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-cm-002', merchant_id: 'merchant-campusmart',
    title: 'CampusMart ErgoLift Aluminum Laptop Stand',
    category: 'student_essentials', subcategory: 'laptop_stand',
    description: 'Aviation-grade aluminum ergonomic laptop stand. 6-level adjustable height and cooling ventilation slots.',
    price: 1999, original_price: 2499, currency: 'INR', stock: 60,
    variants: [],
    attributes: { brand: 'CampusMart', material: 'aluminum', max_laptop_size: '16_inch', adjustable: 'yes' },
    delivery_days: 3, rating: 4.6, image_url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=600&auto=format&fit=crop&q=80', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-cm-003', merchant_id: 'merchant-campusmart',
    title: 'CampusMart Urban Scholar Backpack 28L',
    category: 'clothing', subcategory: 'backpack',
    description: 'Water-resistant urban backpack with dedicated 16" padded laptop sleeve, anti-theft pocket, and USB charging pass.',
    price: 1799, original_price: 2299, currency: 'INR', stock: 100,
    variants: [
      { id: 'v-cm003-blk', product_id: 'prod-cm-003', name: 'Stealth Black', sku: 'CM-CB-BLK', price: 1799, stock: 40, attributes: { color: 'black' } },
      { id: 'v-cm003-nvy', product_id: 'prod-cm-003', name: 'Navy Blue', sku: 'CM-CB-NVY', price: 1799, stock: 35, attributes: { color: 'navy' } },
      { id: 'v-cm003-grn', product_id: 'prod-cm-003', name: 'Olive Green', sku: 'CM-CB-GRN', price: 1799, stock: 25, attributes: { color: 'olive_green' } },
    ],
    attributes: { brand: 'CampusMart', laptop_fit: '16_inch', material: 'canvas', usb_port: 'yes' },
    delivery_days: 3, rating: 4.5, image_url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-cm-004', merchant_id: 'merchant-campusmart',
    title: 'CampusMart BudgetBuds Wireless 2.0',
    category: 'electronics', subcategory: 'earbuds',
    description: 'Reliable everyday wireless earbuds with crisp vocal clarity and 24hr battery with pocket charging case.',
    price: 999, original_price: 1499, currency: 'INR', stock: 200,
    variants: [
      { id: 'v-cm004-blk', product_id: 'prod-cm-004', name: 'Black', sku: 'CM-BB-BLK', price: 999, stock: 80, attributes: { color: 'black' } },
      { id: 'v-cm004-wht', product_id: 'prod-cm-004', name: 'White', sku: 'CM-BB-WHT', price: 999, stock: 60, attributes: { color: 'white' } },
    ],
    attributes: { brand: 'CampusMart', type: 'TWS', battery: '24hrs', waterproof: 'IPX4' },
    delivery_days: 2, rating: 4.1, image_url: 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=600&auto=format&fit=crop&q=80', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-cm-005', merchant_id: 'merchant-campusmart',
    title: 'CampusMart QuickRun Campus Shoes',
    category: 'running_shoes', subcategory: 'daily_training',
    description: 'Ultra-light campus and casual running shoes. Breathable knitted mesh for all-day comfort and walking.',
    price: 1999, original_price: 2499, currency: 'INR', stock: 70,
    variants: [
      { id: 'v-cm005-8', product_id: 'prod-cm-005', name: 'Size 8 - Black', sku: 'CM-QR-8-BLK', price: 1999, stock: 20, attributes: { size: '8', color: 'black' } },
      { id: 'v-cm005-9', product_id: 'prod-cm-005', name: 'Size 9 - Black', sku: 'CM-QR-9-BLK', price: 1999, stock: 25, attributes: { size: '9', color: 'black' } },
      { id: 'v-cm005-10', product_id: 'prod-cm-005', name: 'Size 10 - Black', sku: 'CM-QR-10-BLK', price: 1999, stock: 25, attributes: { size: '10', color: 'black' } },
    ],
    attributes: { brand: 'CampusMart', type: 'daily_trainer', cushioning: 'cloud_eva', weight: '245g', drop: '8mm' },
    delivery_days: 3, rating: 4.3, image_url: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=600&auto=format&fit=crop&q=80', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-cm-006', merchant_id: 'merchant-campusmart',
    title: 'CampusMart NoteBook Pro A4 (5-Pack)',
    category: 'student_essentials', subcategory: 'stationery',
    description: 'Premium ruled notebooks, 200 pages each of smooth 80 GSM acid-free paper with lay-flat binding.',
    price: 499, original_price: 649, currency: 'INR', stock: 300,
    variants: [],
    attributes: { brand: 'CampusMart', pages: '200', size: 'A4', pack: '5' },
    delivery_days: 2, rating: 4.6, image_url: 'https://images.unsplash.com/photo-1456735190827-d1262f71b8a3?w=600&auto=format&fit=crop&q=80', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },

  // ============ FitFuel Nutrition & Gear ============
  {
    id: 'prod-ff-001', merchant_id: 'merchant-fitfuel',
    title: 'FitFuel PowerLoop Resistance Bands (Set of 5)',
    category: 'fitness', subcategory: 'resistance_bands',
    description: 'Heavy-duty 100% natural latex resistance loop bands with 5 color-coded resistance levels (10lbs to 50lbs).',
    price: 899, original_price: 1299, currency: 'INR', stock: 150,
    variants: [],
    attributes: { brand: 'FitFuel', levels: '5', material: 'Natural Latex', bag_included: 'yes' },
    delivery_days: 2, rating: 4.7, image_url: 'https://images.unsplash.com/photo-1598289431512-b97b0917affc?w=600&auto=format&fit=crop&q=80', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-ff-002', merchant_id: 'merchant-fitfuel',
    title: 'FitFuel ProGrip Leather Workout Gloves',
    category: 'fitness', subcategory: 'gloves',
    description: 'Breathable leather workout gloves with integrated wrist wrap support and palm silicone honeycomb grip.',
    price: 699, original_price: 999, currency: 'INR', stock: 120,
    variants: [
      { id: 'v-ff002-m', product_id: 'prod-ff-002', name: 'Medium', sku: 'FF-PG-M', price: 699, stock: 40, attributes: { size: 'M' } },
      { id: 'v-ff002-l', product_id: 'prod-ff-002', name: 'Large', sku: 'FF-PG-L', price: 699, stock: 40, attributes: { size: 'L' } },
      { id: 'v-ff002-xl', product_id: 'prod-ff-002', name: 'X-Large', sku: 'FF-PG-XL', price: 699, stock: 40, attributes: { size: 'XL' } },
    ],
    attributes: { brand: 'FitFuel', material: 'leather_microfiber', wrist_support: 'yes' },
    delivery_days: 2, rating: 4.5, image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600&auto=format&fit=crop&q=80', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-ff-003', merchant_id: 'merchant-fitfuel',
    title: 'FitFuel 100% Whey Protein Isolate 1kg',
    category: 'nutrition', subcategory: 'protein',
    description: 'Ultra-filtered 100% Whey Isolate delivering 27g protein, 5.8g BCAAs, and 0g added sugar per serving. Rapid absorption.',
    price: 2499, original_price: 2999, currency: 'INR', stock: 80,
    variants: [
      { id: 'v-ff003-choc', product_id: 'prod-ff-003', name: 'Double Chocolate', sku: 'FF-WPI-CHOC', price: 2499, stock: 30, attributes: { flavor: 'chocolate' } },
      { id: 'v-ff003-van', product_id: 'prod-ff-003', name: 'French Vanilla', sku: 'FF-WPI-VAN', price: 2499, stock: 25, attributes: { flavor: 'vanilla' } },
      { id: 'v-ff003-unf', product_id: 'prod-ff-003', name: 'Raw Unflavored', sku: 'FF-WPI-UNF', price: 2499, stock: 25, attributes: { flavor: 'unflavored' } },
    ],
    attributes: { brand: 'FitFuel', protein_per_scoop: '27g', weight: '1kg', sugar: '0g' },
    delivery_days: 3, rating: 4.8, image_url: 'https://images.unsplash.com/photo-1579722821273-0f6c7d44362f?w=600&auto=format&fit=crop&q=80', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-ff-004', merchant_id: 'merchant-fitfuel',
    title: 'FitFuel ProGrip Eco Yoga Mat 6mm',
    category: 'fitness', subcategory: 'yoga_mat',
    description: 'High-density biodegradable TPE yoga mat with laser-engraved alignment lines. Non-slip dual texture with carrying strap.',
    price: 1499, original_price: 1999, currency: 'INR', stock: 60,
    variants: [
      { id: 'v-ff004-pur', product_id: 'prod-ff-004', name: 'Royal Purple', sku: 'FF-YM-PUR', price: 1499, stock: 20, attributes: { color: 'purple' } },
      { id: 'v-ff004-blk', product_id: 'prod-ff-004', name: 'Obsidian Black', sku: 'FF-YM-BLK', price: 1499, stock: 20, attributes: { color: 'black' } },
      { id: 'v-ff004-blu', product_id: 'prod-ff-004', name: 'Ocean Blue', sku: 'FF-YM-BLU', price: 1499, stock: 20, attributes: { color: 'blue' } },
    ],
    attributes: { brand: 'FitFuel', thickness: '6mm', material: 'Eco-TPE', alignment_lines: 'yes' },
    delivery_days: 3, rating: 4.7, image_url: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=600&auto=format&fit=crop&q=80', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-ff-005', merchant_id: 'merchant-fitfuel',
    title: 'FitFuel SprintX Cross-Training Shoes',
    category: 'running_shoes', subcategory: 'daily_training',
    description: 'Hybrid training shoe engineered for HIIT, road runs, and gym lifting. Stable flat heel with flexible forefoot.',
    price: 3999, original_price: 4799, currency: 'INR', stock: 40,
    variants: [
      { id: 'v-ff005-8', product_id: 'prod-ff-005', name: 'Size 8 - Black', sku: 'FF-SX-8-BLK', price: 3999, stock: 10, attributes: { size: '8', color: 'black' } },
      { id: 'v-ff005-9', product_id: 'prod-ff-005', name: 'Size 9 - Black', sku: 'FF-SX-9-BLK', price: 3999, stock: 15, attributes: { size: '9', color: 'black' } },
      { id: 'v-ff005-10', product_id: 'prod-ff-005', name: 'Size 10 - Black/Red', sku: 'FF-SX-10-BR', price: 3999, stock: 8, attributes: { size: '10', color: 'black_red' } },
      { id: 'v-ff005-9r', product_id: 'prod-ff-005', name: 'Size 9 - Black/Red', sku: 'FF-SX-9-BR', price: 3999, stock: 7, attributes: { size: '9', color: 'black_red' } },
    ],
    attributes: { brand: 'FitFuel', type: 'cross_trainer', cushioning: 'dual_density', weight: '295g', drop: '4mm' },
    delivery_days: 3, rating: 4.6, image_url: 'https://images.unsplash.com/photo-1595341888016-a392ef81b7de?w=600&auto=format&fit=crop&q=80', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-ff-006', merchant_id: 'merchant-fitfuel',
    title: 'FitFuel Stainless Protein Shaker 700ml',
    category: 'accessories', subcategory: 'shaker',
    description: 'Double-wall vacuum insulated stainless steel shaker bottle. Keeps drinks cold for 24hrs with leak-proof flip cap.',
    price: 899, original_price: 1199, currency: 'INR', stock: 250,
    variants: [
      { id: 'v-ff006-blk', product_id: 'prod-ff-006', name: 'Matte Black', sku: 'FF-SB-BLK', price: 899, stock: 100, attributes: { color: 'black' } },
      { id: 'v-ff006-slv', product_id: 'prod-ff-006', name: 'Brushed Steel', sku: 'FF-SB-SLV', price: 899, stock: 80, attributes: { color: 'silver' } },
    ],
    attributes: { brand: 'FitFuel', capacity: '700ml', material: 'Stainless Steel 304' },
    delivery_days: 2, rating: 4.7, image_url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-ff-007', merchant_id: 'merchant-fitfuel',
    title: 'FitFuel EliteRun Carbon Pro Marathon Shoe',
    category: 'running_shoes', subcategory: 'racing',
    description: 'Full-length curved carbon fiber plate with supercritical foam. Engineered for marathon PB breakthroughs.',
    price: 6999, original_price: 7999, currency: 'INR', stock: 15,
    variants: [
      { id: 'v-ff007-9', product_id: 'prod-ff-007', name: 'Size 9 - Black', sku: 'FF-ERC-9-BLK', price: 6999, stock: 5, attributes: { size: '9', color: 'black' } },
      { id: 'v-ff007-10', product_id: 'prod-ff-007', name: 'Size 10 - Black', sku: 'FF-ERC-10-BLK', price: 6999, stock: 5, attributes: { size: '10', color: 'black' } },
      { id: 'v-ff007-9w', product_id: 'prod-ff-007', name: 'Size 9 - White/Gold', sku: 'FF-ERC-9-WG', price: 6999, stock: 5, attributes: { size: '9', color: 'white_gold' } },
    ],
    attributes: { brand: 'FitFuel', type: 'marathon_racer', cushioning: 'carbon_infused', weight: '210g', drop: '8mm' },
    delivery_days: 3, rating: 4.9, image_url: 'https://images.unsplash.com/photo-1582588678413-dbf45f4823e9?w=600&auto=format&fit=crop&q=80', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
];
