// ============================================================
// AgentGate — Seed Data: 4 Merchants, ~50 Products
// ============================================================

import type { Merchant, MerchantPolicy, Product } from '../types.js';

// ---- Merchants ----
export const seedMerchants: Merchant[] = [
  {
    id: 'merchant-runpro',
    name: 'RunPro Sports',
    slug: 'runpro-sports',
    description: 'Premium running and fitness gear for serious athletes',
    logo_url: '/logos/runpro.png',
    rating: 4.6,
    reliability_score: 0.94,
    categories: ['running_shoes', 'fitness', 'accessories'],
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'merchant-technest',
    name: 'TechNest',
    slug: 'technest',
    description: 'Smart electronics and gadgets at competitive prices',
    logo_url: '/logos/technest.png',
    rating: 4.4,
    reliability_score: 0.91,
    categories: ['electronics', 'accessories'],
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'merchant-campusmart',
    name: 'CampusMart',
    slug: 'campusmart',
    description: 'Everything a student needs — affordable, reliable, fast delivery',
    logo_url: '/logos/campusmart.png',
    rating: 4.2,
    reliability_score: 0.88,
    categories: ['student_essentials', 'electronics', 'clothing'],
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'merchant-fitfuel',
    name: 'FitFuel',
    slug: 'fitfuel',
    description: 'Fitness accessories and nutrition for your health goals',
    logo_url: '/logos/fitfuel.png',
    rating: 4.5,
    reliability_score: 0.92,
    categories: ['fitness', 'nutrition', 'accessories'],
    created_at: '2025-01-01T00:00:00Z',
  },
];

// ---- Merchant Policies ----
export const seedMerchantPolicies: MerchantPolicy[] = [
  {
    id: 'policy-runpro',
    merchant_id: 'merchant-runpro',
    negotiation: true,
    max_discount: 0.10,
    auto_confirmation_limit: 25000,
    auto_refund_limit: 2000,
    upsell: true,
    max_upsell_offers: 2,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'policy-technest',
    merchant_id: 'merchant-technest',
    negotiation: true,
    max_discount: 0.07,
    auto_confirmation_limit: 50000,
    auto_refund_limit: 3000,
    upsell: true,
    max_upsell_offers: 3,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'policy-campusmart',
    merchant_id: 'merchant-campusmart',
    negotiation: true,
    max_discount: 0.12,
    auto_confirmation_limit: 15000,
    auto_refund_limit: 1000,
    upsell: false,
    max_upsell_offers: 0,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'policy-fitfuel',
    merchant_id: 'merchant-fitfuel',
    negotiation: true,
    max_discount: 0.08,
    auto_confirmation_limit: 20000,
    auto_refund_limit: 1500,
    upsell: true,
    max_upsell_offers: 2,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
];

// ---- Products ----
export const seedProducts: Product[] = [
  // ============ RunPro Sports ============
  {
    id: 'prod-rp-001', merchant_id: 'merchant-runpro',
    title: 'RunPro Velocity X Daily Trainer',
    category: 'running_shoes', subcategory: 'daily_training',
    description: 'Lightweight daily training shoe with responsive cushioning and breathable mesh upper. Perfect for everyday runs up to 10K.',
    price: 5799, original_price: 6499, currency: 'INR', stock: 45,
    variants: [
      { id: 'v-rp001-8', product_id: 'prod-rp-001', name: 'Size 8 - Black', sku: 'RP-VX-8-BLK', price: 5799, stock: 12, attributes: { size: '8', color: 'black' } },
      { id: 'v-rp001-9', product_id: 'prod-rp-001', name: 'Size 9 - Black', sku: 'RP-VX-9-BLK', price: 5799, stock: 15, attributes: { size: '9', color: 'black' } },
      { id: 'v-rp001-10', product_id: 'prod-rp-001', name: 'Size 10 - Black', sku: 'RP-VX-10-BLK', price: 5799, stock: 10, attributes: { size: '10', color: 'black' } },
      { id: 'v-rp001-9w', product_id: 'prod-rp-001', name: 'Size 9 - White', sku: 'RP-VX-9-WHT', price: 5799, stock: 8, attributes: { size: '9', color: 'white' } },
    ],
    attributes: { brand: 'RunPro', type: 'daily_trainer', cushioning: 'responsive', weight: '280g', drop: '8mm' },
    delivery_days: 3, rating: 4.5, image_url: '/products/runpro-velocity-x.jpg', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-rp-002', merchant_id: 'merchant-runpro',
    title: 'RunPro Surge Pro Racing Flat',
    category: 'running_shoes', subcategory: 'racing',
    description: 'Carbon-plated racing shoe for competitive runners. Ultra-light with maximum energy return.',
    price: 8999, original_price: 9999, currency: 'INR', stock: 20,
    variants: [
      { id: 'v-rp002-9', product_id: 'prod-rp-002', name: 'Size 9 - Neon Green', sku: 'RP-SP-9-NGR', price: 8999, stock: 8, attributes: { size: '9', color: 'neon_green' } },
      { id: 'v-rp002-10', product_id: 'prod-rp-002', name: 'Size 10 - Neon Green', sku: 'RP-SP-10-NGR', price: 8999, stock: 6, attributes: { size: '10', color: 'neon_green' } },
    ],
    attributes: { brand: 'RunPro', type: 'racing', cushioning: 'carbon_plate', weight: '195g', drop: '6mm' },
    delivery_days: 2, rating: 4.8, image_url: '/products/runpro-surge-pro.jpg', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-rp-003', merchant_id: 'merchant-runpro',
    title: 'RunPro CloudStride Comfort',
    category: 'running_shoes', subcategory: 'daily_training',
    description: 'Maximum cushioning for long-distance daily training. Cloud-foam midsole absorbs impact beautifully.',
    price: 4999, original_price: 5999, currency: 'INR', stock: 60,
    variants: [
      { id: 'v-rp003-8', product_id: 'prod-rp-003', name: 'Size 8 - Black', sku: 'RP-CS-8-BLK', price: 4999, stock: 15, attributes: { size: '8', color: 'black' } },
      { id: 'v-rp003-9', product_id: 'prod-rp-003', name: 'Size 9 - Black', sku: 'RP-CS-9-BLK', price: 4999, stock: 20, attributes: { size: '9', color: 'black' } },
      { id: 'v-rp003-9g', product_id: 'prod-rp-003', name: 'Size 9 - Grey', sku: 'RP-CS-9-GRY', price: 4999, stock: 15, attributes: { size: '9', color: 'grey' } },
      { id: 'v-rp003-10', product_id: 'prod-rp-003', name: 'Size 10 - Black', sku: 'RP-CS-10-BLK', price: 4999, stock: 10, attributes: { size: '10', color: 'black' } },
    ],
    attributes: { brand: 'RunPro', type: 'daily_trainer', cushioning: 'cloud_foam', weight: '310g', drop: '10mm' },
    delivery_days: 3, rating: 4.3, image_url: '/products/runpro-cloudstride.jpg', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-rp-004', merchant_id: 'merchant-runpro',
    title: 'RunPro TrailBlazer GTX',
    category: 'running_shoes', subcategory: 'trail',
    description: 'Waterproof trail running shoe with aggressive grip. Built for off-road terrain.',
    price: 6999, original_price: 7999, currency: 'INR', stock: 25,
    variants: [
      { id: 'v-rp004-9', product_id: 'prod-rp-004', name: 'Size 9 - Black/Orange', sku: 'RP-TB-9-BOR', price: 6999, stock: 10, attributes: { size: '9', color: 'black_orange' } },
      { id: 'v-rp004-10', product_id: 'prod-rp-004', name: 'Size 10 - Black/Orange', sku: 'RP-TB-10-BOR', price: 6999, stock: 8, attributes: { size: '10', color: 'black_orange' } },
    ],
    attributes: { brand: 'RunPro', type: 'trail', cushioning: 'rock_plate', weight: '340g', drop: '6mm', waterproof: 'yes' },
    delivery_days: 4, rating: 4.6, image_url: '/products/runpro-trailblazer.jpg', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-rp-005', merchant_id: 'merchant-runpro',
    title: 'RunPro FlexRun Lite',
    category: 'running_shoes', subcategory: 'daily_training',
    description: 'Budget-friendly daily trainer with decent cushioning. Great entry-level running shoe.',
    price: 2999, original_price: 3499, currency: 'INR', stock: 80,
    variants: [
      { id: 'v-rp005-8', product_id: 'prod-rp-005', name: 'Size 8 - Black', sku: 'RP-FL-8-BLK', price: 2999, stock: 25, attributes: { size: '8', color: 'black' } },
      { id: 'v-rp005-9', product_id: 'prod-rp-005', name: 'Size 9 - Black', sku: 'RP-FL-9-BLK', price: 2999, stock: 30, attributes: { size: '9', color: 'black' } },
      { id: 'v-rp005-10', product_id: 'prod-rp-005', name: 'Size 10 - Blue', sku: 'RP-FL-10-BLU', price: 2999, stock: 25, attributes: { size: '10', color: 'blue' } },
    ],
    attributes: { brand: 'RunPro', type: 'daily_trainer', cushioning: 'eva_foam', weight: '260g', drop: '8mm' },
    delivery_days: 2, rating: 4.0, image_url: '/products/runpro-flexrun.jpg', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-rp-006', merchant_id: 'merchant-runpro',
    title: 'RunPro Compression Running Socks (3-Pack)',
    category: 'accessories', subcategory: 'socks',
    description: 'Moisture-wicking compression socks designed for runners. Arch support and blister prevention.',
    price: 799, original_price: 999, currency: 'INR', stock: 200,
    variants: [],
    attributes: { brand: 'RunPro', material: 'nylon_blend', compression: 'medium' },
    delivery_days: 2, rating: 4.4, image_url: '/products/runpro-socks.jpg', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-rp-007', merchant_id: 'merchant-runpro',
    title: 'RunPro HydraFlask Running Bottle 500ml',
    category: 'accessories', subcategory: 'hydration',
    description: 'Ergonomic squeeze bottle designed for running. Soft flask with bite valve.',
    price: 599, original_price: 699, currency: 'INR', stock: 150,
    variants: [],
    attributes: { brand: 'RunPro', capacity: '500ml', material: 'BPA-free silicone' },
    delivery_days: 2, rating: 4.2, image_url: '/products/runpro-flask.jpg', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },

  // ============ TechNest ============
  {
    id: 'prod-tn-001', merchant_id: 'merchant-technest',
    title: 'TechNest AirBuds Pro X',
    category: 'electronics', subcategory: 'earbuds',
    description: 'Active noise cancelling wireless earbuds with 30hr battery. Premium sound quality.',
    price: 4499, original_price: 5499, currency: 'INR', stock: 100,
    variants: [
      { id: 'v-tn001-blk', product_id: 'prod-tn-001', name: 'Black', sku: 'TN-ABP-BLK', price: 4499, stock: 40, attributes: { color: 'black' } },
      { id: 'v-tn001-wht', product_id: 'prod-tn-001', name: 'White', sku: 'TN-ABP-WHT', price: 4499, stock: 35, attributes: { color: 'white' } },
    ],
    attributes: { brand: 'TechNest', type: 'TWS', anc: 'yes', battery: '30hrs', driver: '11mm' },
    delivery_days: 2, rating: 4.5, image_url: '/products/technest-airbuds.jpg', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-tn-002', merchant_id: 'merchant-technest',
    title: 'TechNest SmartBand Pulse',
    category: 'electronics', subcategory: 'wearable',
    description: 'Fitness tracker with heart rate, SpO2, sleep tracking, and 14-day battery life.',
    price: 2999, original_price: 3999, currency: 'INR', stock: 75,
    variants: [
      { id: 'v-tn002-blk', product_id: 'prod-tn-002', name: 'Black Strap', sku: 'TN-SBP-BLK', price: 2999, stock: 35, attributes: { color: 'black' } },
      { id: 'v-tn002-grn', product_id: 'prod-tn-002', name: 'Green Strap', sku: 'TN-SBP-GRN', price: 2999, stock: 20, attributes: { color: 'green' } },
    ],
    attributes: { brand: 'TechNest', type: 'fitness_tracker', heart_rate: 'yes', spo2: 'yes', battery: '14days' },
    delivery_days: 2, rating: 4.3, image_url: '/products/technest-smartband.jpg', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-tn-003', merchant_id: 'merchant-technest',
    title: 'TechNest PowerBank 20000mAh',
    category: 'electronics', subcategory: 'power_bank',
    description: '20000mAh power bank with 65W fast charging. Charges laptops and phones.',
    price: 1999, original_price: 2499, currency: 'INR', stock: 120,
    variants: [],
    attributes: { brand: 'TechNest', capacity: '20000mAh', fast_charge: '65W', ports: 'USB-C, USB-A' },
    delivery_days: 3, rating: 4.4, image_url: '/products/technest-powerbank.jpg', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-tn-004', merchant_id: 'merchant-technest',
    title: 'TechNest MiniSpeaker Blast',
    category: 'electronics', subcategory: 'speaker',
    description: 'Portable Bluetooth speaker with deep bass and IPX7 waterproofing. 12hr battery.',
    price: 3499, original_price: 4499, currency: 'INR', stock: 55,
    variants: [
      { id: 'v-tn004-blk', product_id: 'prod-tn-004', name: 'Black', sku: 'TN-MSB-BLK', price: 3499, stock: 25, attributes: { color: 'black' } },
      { id: 'v-tn004-red', product_id: 'prod-tn-004', name: 'Red', sku: 'TN-MSB-RED', price: 3499, stock: 15, attributes: { color: 'red' } },
    ],
    attributes: { brand: 'TechNest', type: 'portable_speaker', waterproof: 'IPX7', battery: '12hrs', bluetooth: '5.3' },
    delivery_days: 3, rating: 4.2, image_url: '/products/technest-speaker.jpg', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-tn-005', merchant_id: 'merchant-technest',
    title: 'TechNest UltraCharge 45W Adapter',
    category: 'electronics', subcategory: 'charger',
    description: 'GaN 45W USB-C fast charger. Compact and travel-friendly.',
    price: 1299, original_price: 1599, currency: 'INR', stock: 200,
    variants: [],
    attributes: { brand: 'TechNest', type: 'charger', wattage: '45W', technology: 'GaN', ports: 'USB-C' },
    delivery_days: 2, rating: 4.6, image_url: '/products/technest-charger.jpg', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-tn-006', merchant_id: 'merchant-technest',
    title: 'TechNest ProWatch Ultra',
    category: 'electronics', subcategory: 'smartwatch',
    description: 'Premium smartwatch with AMOLED display, GPS, and 7-day battery. Stainless steel build.',
    price: 8499, original_price: 9999, currency: 'INR', stock: 30,
    variants: [
      { id: 'v-tn006-blk', product_id: 'prod-tn-006', name: 'Black Steel', sku: 'TN-PWU-BLK', price: 8499, stock: 15, attributes: { color: 'black', material: 'stainless_steel' } },
      { id: 'v-tn006-slv', product_id: 'prod-tn-006', name: 'Silver Steel', sku: 'TN-PWU-SLV', price: 8499, stock: 15, attributes: { color: 'silver', material: 'stainless_steel' } },
    ],
    attributes: { brand: 'TechNest', type: 'smartwatch', display: 'AMOLED', gps: 'yes', battery: '7days' },
    delivery_days: 3, rating: 4.7, image_url: '/products/technest-prowatch.jpg', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },

  // ============ CampusMart ============
  {
    id: 'prod-cm-001', merchant_id: 'merchant-campusmart',
    title: 'CampusMart StudyLamp LED Pro',
    category: 'student_essentials', subcategory: 'lamp',
    description: 'Adjustable LED desk lamp with 5 brightness levels and USB charging port.',
    price: 1499, original_price: 1999, currency: 'INR', stock: 90,
    variants: [],
    attributes: { brand: 'CampusMart', type: 'desk_lamp', brightness_levels: '5', usb_port: 'yes' },
    delivery_days: 3, rating: 4.1, image_url: '/products/campusmart-lamp.jpg', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-cm-002', merchant_id: 'merchant-campusmart',
    title: 'CampusMart ErgoBack Laptop Stand',
    category: 'student_essentials', subcategory: 'laptop_stand',
    description: 'Ergonomic aluminum laptop stand. Adjustable height and angle. Fits up to 16" laptops.',
    price: 1999, original_price: 2499, currency: 'INR', stock: 60,
    variants: [],
    attributes: { brand: 'CampusMart', material: 'aluminum', max_laptop_size: '16_inch', adjustable: 'yes' },
    delivery_days: 4, rating: 4.3, image_url: '/products/campusmart-stand.jpg', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-cm-003', merchant_id: 'merchant-campusmart',
    title: 'CampusMart Canvas Backpack',
    category: 'clothing', subcategory: 'backpack',
    description: 'Durable canvas backpack with laptop compartment, water bottle holder, and USB charging port.',
    price: 1799, original_price: 2299, currency: 'INR', stock: 100,
    variants: [
      { id: 'v-cm003-blk', product_id: 'prod-cm-003', name: 'Black', sku: 'CM-CB-BLK', price: 1799, stock: 40, attributes: { color: 'black' } },
      { id: 'v-cm003-nvy', product_id: 'prod-cm-003', name: 'Navy', sku: 'CM-CB-NVY', price: 1799, stock: 35, attributes: { color: 'navy' } },
      { id: 'v-cm003-grn', product_id: 'prod-cm-003', name: 'Olive Green', sku: 'CM-CB-GRN', price: 1799, stock: 25, attributes: { color: 'olive_green' } },
    ],
    attributes: { brand: 'CampusMart', laptop_fit: '15.6_inch', material: 'canvas', usb_port: 'yes' },
    delivery_days: 3, rating: 4.0, image_url: '/products/campusmart-backpack.jpg', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-cm-004', merchant_id: 'merchant-campusmart',
    title: 'CampusMart BudgetBuds Wireless',
    category: 'electronics', subcategory: 'earbuds',
    description: 'Affordable wireless earbuds with decent sound and 20hr battery. IPX4 sweat resistant.',
    price: 999, original_price: 1499, currency: 'INR', stock: 200,
    variants: [
      { id: 'v-cm004-blk', product_id: 'prod-cm-004', name: 'Black', sku: 'CM-BB-BLK', price: 999, stock: 80, attributes: { color: 'black' } },
      { id: 'v-cm004-wht', product_id: 'prod-cm-004', name: 'White', sku: 'CM-BB-WHT', price: 999, stock: 60, attributes: { color: 'white' } },
    ],
    attributes: { brand: 'CampusMart', type: 'TWS', battery: '20hrs', waterproof: 'IPX4' },
    delivery_days: 2, rating: 3.9, image_url: '/products/campusmart-buds.jpg', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-cm-005', merchant_id: 'merchant-campusmart',
    title: 'CampusMart QuickRun Campus Shoes',
    category: 'running_shoes', subcategory: 'daily_training',
    description: 'Affordable campus running shoes. Lightweight and comfortable for daily use.',
    price: 1999, original_price: 2499, currency: 'INR', stock: 70,
    variants: [
      { id: 'v-cm005-8', product_id: 'prod-cm-005', name: 'Size 8 - Black', sku: 'CM-QR-8-BLK', price: 1999, stock: 20, attributes: { size: '8', color: 'black' } },
      { id: 'v-cm005-9', product_id: 'prod-cm-005', name: 'Size 9 - Black', sku: 'CM-QR-9-BLK', price: 1999, stock: 25, attributes: { size: '9', color: 'black' } },
      { id: 'v-cm005-10', product_id: 'prod-cm-005', name: 'Size 10 - Black', sku: 'CM-QR-10-BLK', price: 1999, stock: 25, attributes: { size: '10', color: 'black' } },
    ],
    attributes: { brand: 'CampusMart', type: 'daily_trainer', cushioning: 'basic_foam', weight: '250g', drop: '8mm' },
    delivery_days: 3, rating: 3.8, image_url: '/products/campusmart-quickrun.jpg', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-cm-006', merchant_id: 'merchant-campusmart',
    title: 'CampusMart NoteBook Pro A4 (5-Pack)',
    category: 'student_essentials', subcategory: 'stationery',
    description: 'Premium ruled notebooks, 200 pages each. Acid-free paper.',
    price: 499, original_price: 649, currency: 'INR', stock: 300,
    variants: [],
    attributes: { brand: 'CampusMart', pages: '200', size: 'A4', pack: '5' },
    delivery_days: 2, rating: 4.2, image_url: '/products/campusmart-notebook.jpg', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },

  // ============ FitFuel ============
  {
    id: 'prod-ff-001', merchant_id: 'merchant-fitfuel',
    title: 'FitFuel Resistance Bands Set (5 Levels)',
    category: 'fitness', subcategory: 'resistance_bands',
    description: 'Set of 5 resistance bands from light to heavy. Latex-free, with carrying bag.',
    price: 899, original_price: 1299, currency: 'INR', stock: 150,
    variants: [],
    attributes: { brand: 'FitFuel', levels: '5', material: 'TPE', bag_included: 'yes' },
    delivery_days: 2, rating: 4.3, image_url: '/products/fitfuel-bands.jpg', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-ff-002', merchant_id: 'merchant-fitfuel',
    title: 'FitFuel ProGrip Training Gloves',
    category: 'fitness', subcategory: 'gloves',
    description: 'Breathable workout gloves with wrist support. Anti-slip grip for weightlifting.',
    price: 699, original_price: 999, currency: 'INR', stock: 120,
    variants: [
      { id: 'v-ff002-m', product_id: 'prod-ff-002', name: 'Medium', sku: 'FF-PG-M', price: 699, stock: 40, attributes: { size: 'M' } },
      { id: 'v-ff002-l', product_id: 'prod-ff-002', name: 'Large', sku: 'FF-PG-L', price: 699, stock: 40, attributes: { size: 'L' } },
      { id: 'v-ff002-xl', product_id: 'prod-ff-002', name: 'X-Large', sku: 'FF-PG-XL', price: 699, stock: 40, attributes: { size: 'XL' } },
    ],
    attributes: { brand: 'FitFuel', material: 'microfiber', wrist_support: 'yes' },
    delivery_days: 2, rating: 4.1, image_url: '/products/fitfuel-gloves.jpg', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-ff-003', merchant_id: 'merchant-fitfuel',
    title: 'FitFuel Whey Protein Isolate 1kg',
    category: 'nutrition', subcategory: 'protein',
    description: 'Pure whey protein isolate. 25g protein per scoop. Low carb, zero sugar.',
    price: 2499, original_price: 2999, currency: 'INR', stock: 80,
    variants: [
      { id: 'v-ff003-choc', product_id: 'prod-ff-003', name: 'Chocolate', sku: 'FF-WPI-CHOC', price: 2499, stock: 30, attributes: { flavor: 'chocolate' } },
      { id: 'v-ff003-van', product_id: 'prod-ff-003', name: 'Vanilla', sku: 'FF-WPI-VAN', price: 2499, stock: 25, attributes: { flavor: 'vanilla' } },
      { id: 'v-ff003-unf', product_id: 'prod-ff-003', name: 'Unflavored', sku: 'FF-WPI-UNF', price: 2499, stock: 25, attributes: { flavor: 'unflavored' } },
    ],
    attributes: { brand: 'FitFuel', protein_per_scoop: '25g', weight: '1kg', sugar: '0g' },
    delivery_days: 3, rating: 4.5, image_url: '/products/fitfuel-protein.jpg', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-ff-004', merchant_id: 'merchant-fitfuel',
    title: 'FitFuel Yoga Mat Premium 6mm',
    category: 'fitness', subcategory: 'yoga_mat',
    description: 'Non-slip yoga mat with alignment lines. 6mm thick, eco-friendly TPE material.',
    price: 1499, original_price: 1999, currency: 'INR', stock: 60,
    variants: [
      { id: 'v-ff004-pur', product_id: 'prod-ff-004', name: 'Purple', sku: 'FF-YM-PUR', price: 1499, stock: 20, attributes: { color: 'purple' } },
      { id: 'v-ff004-blk', product_id: 'prod-ff-004', name: 'Black', sku: 'FF-YM-BLK', price: 1499, stock: 20, attributes: { color: 'black' } },
      { id: 'v-ff004-blu', product_id: 'prod-ff-004', name: 'Blue', sku: 'FF-YM-BLU', price: 1499, stock: 20, attributes: { color: 'blue' } },
    ],
    attributes: { brand: 'FitFuel', thickness: '6mm', material: 'TPE', alignment_lines: 'yes' },
    delivery_days: 3, rating: 4.4, image_url: '/products/fitfuel-yogamat.jpg', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-ff-005', merchant_id: 'merchant-fitfuel',
    title: 'FitFuel SprintX Running Shoes',
    category: 'running_shoes', subcategory: 'daily_training',
    description: 'Versatile training shoe designed for gym-to-street. Flexible sole with good grip.',
    price: 3999, original_price: 4799, currency: 'INR', stock: 40,
    variants: [
      { id: 'v-ff005-8', product_id: 'prod-ff-005', name: 'Size 8 - Black', sku: 'FF-SX-8-BLK', price: 3999, stock: 10, attributes: { size: '8', color: 'black' } },
      { id: 'v-ff005-9', product_id: 'prod-ff-005', name: 'Size 9 - Black', sku: 'FF-SX-9-BLK', price: 3999, stock: 15, attributes: { size: '9', color: 'black' } },
      { id: 'v-ff005-10', product_id: 'prod-ff-005', name: 'Size 10 - Black/Red', sku: 'FF-SX-10-BR', price: 3999, stock: 8, attributes: { size: '10', color: 'black_red' } },
      { id: 'v-ff005-9r', product_id: 'prod-ff-005', name: 'Size 9 - Black/Red', sku: 'FF-SX-9-BR', price: 3999, stock: 7, attributes: { size: '9', color: 'black_red' } },
    ],
    attributes: { brand: 'FitFuel', type: 'daily_trainer', cushioning: 'dual_density', weight: '295g', drop: '8mm' },
    delivery_days: 3, rating: 4.2, image_url: '/products/fitfuel-sprintx.jpg', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-ff-006', merchant_id: 'merchant-fitfuel',
    title: 'FitFuel Shaker Bottle 700ml',
    category: 'accessories', subcategory: 'shaker',
    description: 'BPA-free protein shaker with mixing ball. Leak-proof lid and measurement markings.',
    price: 399, original_price: 499, currency: 'INR', stock: 250,
    variants: [
      { id: 'v-ff006-blk', product_id: 'prod-ff-006', name: 'Black', sku: 'FF-SB-BLK', price: 399, stock: 100, attributes: { color: 'black' } },
      { id: 'v-ff006-blu', product_id: 'prod-ff-006', name: 'Blue', sku: 'FF-SB-BLU', price: 399, stock: 80, attributes: { color: 'blue' } },
    ],
    attributes: { brand: 'FitFuel', capacity: '700ml', material: 'BPA-free plastic' },
    delivery_days: 2, rating: 4.0, image_url: '/products/fitfuel-shaker.jpg', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-ff-007', merchant_id: 'merchant-fitfuel',
    title: 'FitFuel EliteRun Carbon Pro',
    category: 'running_shoes', subcategory: 'daily_training',
    description: 'Premium daily training shoe with carbon-fiber infused midsole. Superior energy return and stability.',
    price: 6999, original_price: 7999, currency: 'INR', stock: 15,
    variants: [
      { id: 'v-ff007-9', product_id: 'prod-ff-007', name: 'Size 9 - Black', sku: 'FF-ERC-9-BLK', price: 6999, stock: 5, attributes: { size: '9', color: 'black' } },
      { id: 'v-ff007-10', product_id: 'prod-ff-007', name: 'Size 10 - Black', sku: 'FF-ERC-10-BLK', price: 6999, stock: 5, attributes: { size: '10', color: 'black' } },
      { id: 'v-ff007-9w', product_id: 'prod-ff-007', name: 'Size 9 - White/Gold', sku: 'FF-ERC-9-WG', price: 6999, stock: 5, attributes: { size: '9', color: 'white_gold' } },
    ],
    attributes: { brand: 'FitFuel', type: 'daily_trainer', cushioning: 'carbon_infused', weight: '265g', drop: '7mm' },
    delivery_days: 4, rating: 4.7, image_url: '/products/fitfuel-eliterun.jpg', ai_searchable: true,
    created_at: '2025-01-01T00:00:00Z',
  },
];
